const app=document.getElementById("app"),title=document.getElementById("title");
let records=[
{id:"HC-2026-014",hospital:"Sunrise Multispeciality Hospital",type:"Certification",status:"Clarification",owner:"Specialist Review",submitted:"03 Oct 2026"},
{id:"HC-2026-012",hospital:"Riverbend Medical Centre",type:"Renewal",status:"Under review",owner:"Specialist Review",submitted:"02 Oct 2026"},
{id:"HC-2026-009",hospital:"Northstar Hospital",type:"Certification",status:"Approved",owner:"Approving Authority",submitted:"30 Sep 2026"},
{id:"HC-2026-006",hospital:"CityCare Hospital",type:"Registration",status:"Evidence pending",owner:"Hospital Admin",submitted:"29 Sep 2026"}
];
let events=[
["Clarification requested","HC-2026-014 · Specialist Review · 11:12"],
["Evidence accepted","HC-2026-012 · Specialist Review · 10:26"],
["Case approved","HC-2026-009 · Approving Authority · 09:41"]
];
const steps=["Evidence pending","Under review","Clarification","Approved"];
function badge(s){const c=s==="Approved"?"ok":s==="Clarification"||s==="Evidence pending"?"warn":"";return '<span class="pill '+c+'">'+s+"</span>"}
function overview(){app.innerHTML='<div class="grid"><div class="card"><div class="label">Active cases</div><div class="num">'+records.length+'</div></div><div class="card"><div class="label">Under review</div><div class="num">'+records.filter(x=>x.status==="Under review").length+'</div></div><div class="card"><div class="label">Clarifications</div><div class="num">'+records.filter(x=>x.status==="Clarification").length+'</div></div><div class="card"><div class="label">Approved</div><div class="num">'+records.filter(x=>x.status==="Approved").length+'</div></div></div><div class="layout"><div class="card"><div class="card-head"><h2>Recent cases</h2><span class="muted">Synthetic data</span></div>'+records.map((x,i)=>'<div class="row"><div><button class="action" data-open="'+i+'"><strong>'+x.id+'</strong></button><div class="muted">'+x.hospital+' · '+x.type+'</div></div>'+badge(x.status)+'</div>').join("")+'</div><div class="card"><h2>Review workload</h2><div class="row"><span>Eligibility</span><strong>4</strong></div><div class="row"><span>Specialist review</span><strong>5</strong></div><div class="row"><span>Clarification</span><strong>3</strong></div><div class="row"><span>Approval</span><strong>2</strong></div></div></div>';bindOpen()}
function table(view){let rows=view==="cases"?records:view==="review"?records.filter(x=>x.status==="Under review"):records.filter(x=>x.status==="Clarification"||x.status==="Evidence pending");app.innerHTML='<div class="card"><div class="card-head"><h2>'+title.textContent+'</h2><span class="muted">'+rows.length+' records</span></div><table class="table"><thead><tr><th>Case</th><th>Hospital</th><th>Type</th><th>Status</th><th>Owner</th><th></th></tr></thead><tbody>'+rows.map(x=>{const i=records.indexOf(x);return '<tr><td><button class="action" data-open="'+i+'"><strong>'+x.id+'</strong></button></td><td>'+x.hospital+'</td><td>'+x.type+'</td><td>'+badge(x.status)+'</td><td>'+x.owner+'</td><td><button class="action" data-open="'+i+'">Open</button></td></tr>'}).join("")+'</tbody></table></div>';bindOpen()}
function bindOpen(){document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>detail(Number(b.dataset.open)))}
function detail(i){const x=records[i],current=steps.indexOf(x.status),next=steps[current+1];title.textContent=x.id;app.innerHTML='<div class="layout"><div class="card"><p class="eyebrow">CASE DETAIL</p><h2>'+x.hospital+'</h2><div class="row"><span>Application</span><strong>'+x.type+'</strong></div><div class="row"><span>Submitted</span><strong>'+x.submitted+'</strong></div><div class="row"><span>Owner</span><strong>'+x.owner+'</strong></div><div class="row"><span>Status</span>'+badge(x.status)+'</div><div class="workflow"><div class="workflow-title">Workflow</div><div class="steps">'+steps.map((s,n)=>'<span class="'+(n<current?"done ":n===current?"current ":"")+'">'+s+'</span>').join("")+'</div></div><div class="evidence"><div><strong>Evidence checklist</strong><span class="muted"> 3 of 4 reviewed</span></div><label><input type="checkbox" checked> Facility documentation</label><label><input type="checkbox" checked> Specialist credentials</label><label><input type="checkbox" checked> Operational records</label><label><input type="checkbox"> Renewal / exception note</label></div><div class="actions">'+(next?'<button class="primary" id="advance">Move to '+next+'</button>':"")+'<button class="action" id="back">Back</button></div></div><div class="card"><div class="card-head"><h2>Decision history</h2><span class="muted">Audit trail</span></div><div class="timeline">'+events.map(e=>'<div class="event"><strong>'+e[0]+'</strong><div class="muted">'+e[1]+'</div></div>').join("")+'</div></div></div>';if(next)document.getElementById("advance").onclick=()=>{x.status=next;x.owner=next==="Approved"?"Approving Authority":next==="Clarification"?"Hospital Admin":"Specialist Review";events.unshift(["Workflow advanced",x.id+" · current reviewer · just now"]);detail(i)};document.getElementById("back").onclick=overview}
function audit(){app.innerHTML='<div class="card"><div class="card-head"><h2>Recent audit events</h2><span class="muted">Session activity</span></div><div class="timeline">'+events.map(e=>'<div class="event"><strong>'+e[0]+'</strong><div class="muted">'+e[1]+'</div></div>').join("")+'</div></div>'}
function newCase(){title.textContent="New case";app.innerHTML='<form class="card form" id="caseForm"><div class="notice">Demo form. No real hospital, patient or credential data is used.</div><div class="field"><label>Hospital name</label><input id="hospital" required placeholder="Fictional hospital name"></div><div class="field"><label>Application type</label><select id="type"><option>Certification</option><option>Renewal</option><option>Registration</option></select></div><div class="field"><label>Reviewer</label><select id="reviewer"><option>Specialist Review</option><option>Hospital Admin</option></select></div><div class="field"><label>Notes</label><textarea id="notes" placeholder="Case notes..."></textarea></div><button class="primary">Create case</button></form>';document.getElementById("caseForm").onsubmit=e=>{e.preventDefault();const id="HC-2026-"+String(15+records.length).padStart(3,"0");records.unshift({id,hospital:document.getElementById("hospital").value,type:document.getElementById("type").value,status:"Evidence pending",owner:document.getElementById("reviewer").value,submitted:"05 Oct 2026"});events.unshift(["Case created",id+" · local demo · just now"]);load("cases")}}
function load(v){title.textContent=v==="overview"?"Overview":v[0].toUpperCase()+v.slice(1);v==="overview"?overview():v==="audit"?audit():v==="cases"||v==="review"||v==="exceptions"?table(v):overview()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");load(b.dataset.view)});document.getElementById("newBtn").onclick=newCase;overview();